const Premium =() =>{
    return(
        <>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
            <h1>Pr</h1>
        </>
    )
}

export default Premium;